include $(NPC_HOME)/script/config.mk

SRC_AUTO_BIND = $(BUILD_DIR)/auto_bind.cpp
ifeq ($(NVBOARD),1)
VERILATOR_SRC += $(SRC_AUTO_BIND)
endif

PREFIX_NAME = Vtop
BIN = $(BUILD_DIR)/$(PREFIX_NAME)
VERILATOR_CFLAGS = -std=c++20 $(CWARNING) -D$(TOP_NAME) -I$(INCLUDE_DIR) $(COPTIMIZE)
VERILATOR_LDFLAGS =  
VERILATOR_SRC = $(VSRC) $(CSRC)
VERILATOR_FLAGS = --cc --exe --Mdir $(OBJ_DIR) -y $(INCLUDE_DIR) --prefix $(PREFIX_NAME) --top-module $(STUDENT_ID)_$(TOP_NAME) -o $(BIN) -j 0 $(VOPTIMIZE) $(VWARNING) $(addprefix -CFLAGS , $(VERILATOR_CFLAGS))
VERILATOR_FLAGS_LIB = $(addprefix -LDFLAGS , $(VERILATOR_LDFLAGS))
VERILATE = $(OBJ_DIR)/verilate.txt

ifeq ($(TOP_NAME),cpu)
VERILATOR_CFLAGS += -DSIM_ALL=1
VERILATOR_LDFLAGS += -lreadline
endif
ifeq ($(ISA),RV32I)
VERILATOR_CFLAGS += -DCONFIG_ISA=0
else ifeq ($(ISA),RV32E)
VERILATOR_CFLAGS += -DCONFIG_ISA=1
else ifeq ($(ISA),RV64I)
VERILATOR_CFLAGS += -DCONFIG_ISA=2
else
$(error "do not support ISA $(ISA)")
endif
ifeq ($(NVBOARD),1)
VERILATOR_CFLAGS += -I$(NVBOARD_HOME)/include -DNV_SIM=1
VERILATOR_LDFLAGS += -lSDL2 -lSDL2_image
VERILATOR_SRC += $(NVBOARD_ARCHIVE)
endif
ifeq ($(HAVE_CLK),1)
VERILATOR_CFLAGS += -DHAVE_CLK=1
endif
ifeq ($(RECORD_WAVE),1)
VERILATOR_CFLAGS += -DCONFIG_RECORD_WAVE=1
VERILATOR_FLAGS += --trace
endif
ifeq ($(LINKOPT),1)
VERILATOR_CFLAGS += -flto
endif
ifeq ($(DEBUG),1)
VERILATOR_CFLAGS += -ggdb3
VERILATOR_FLAGS += --debug
endif
ifeq ($(FSANITIZE),1)
VERILATOR_CFLAGS += -fsanitize=address
VERILATOR_LDFLAGS += -fsanitize=address
endif
ifeq ($(TRACE),1)
VERILATOR_CFLAGS += -DCONFIG_TRACE=1
endif
ifeq ($(EXPR_MATCH),1)
VERILATOR_CFLAGS += -DCONFIG_EXPR_MATCH=1
endif
ifeq ($(ITRACE),1)
VERILATOR_CFLAGS += -I/usr/lib/llvm-14/include -DCONFIG_ITRACE=1
VERILATOR_LDFLAGS += -lLLVM-14
endif
ifeq ($(MTRACE),1)
VERILATOR_CFLAGS += -DCONFIG_MTRACE=1
endif
ifeq ($(FTRACE),1)
VERILATOR_CFLAGS += -DCONFIG_FTRACE=1
endif
ifeq ($(WATCHPOINT),1)
VERILATOR_CFLAGS += -DCONFIG_WATCHPOINT=1
endif
ifeq ($(DIFFTEST),1)
VERILATOR_CFLAGS += -DCONFIG_DIFFTEST=1
endif
ifeq ($(MEM_RANDOM),1)
VERILATOR_CFLAGS += -DCONFIG_MEM_RANDOM=1
endif

VERILATOR_MAKE_FILE = $(OBJ_DIR)/$(PREFIX_NAME).mk
MAKE_FLAGS = -C $(OBJ_DIR) -f $(VERILATOR_MAKE_FILE) -j $(shell nproc)

override NPC_FLAGS ?= --log=$(BUILD_DIR)/npc-log.txt
override NPC_FLAGS += -d $(NEMU_HOME)/build/riscv32-nemu-interpreter-so
IMG ?= 
WAVE = $(BUILD_DIR)/wave.vcd
